#version 450

struct SphereNode {
    vec4 pos;
    vec4 color;
    vec4 vel;
    vec4 originPos;
    vec4 prevPos;
    vec4 normal;
    float isFixed;
    float isSurface;
    float padding[2];
};

struct DistanceConstraint {
    uint idx1;
    uint idx2;
    float restLength;
    float lambda;
};

// C++에서 설정한 Descriptor Sets와 매칭
layout(std430, binding = 0) readonly buffer InputNodes {
    SphereNode nodesIn[];
};

layout(std430, binding = 1) writeonly buffer OutputNodes {
    SphereNode nodesOut[];
};

layout(std430, binding = 2) buffer DistanceConstraints {
    DistanceConstraint constraints[];
};

// dt(타임스텝)를 받는 Push Constant
layout(push_constant) uniform PushConstants {
    float dt;
    float u_Time; // 누적된 전체 시간
    int passType;
    int subStepCnt;
};

// 워크그룹 크기 설정
layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

// 시뮬레이션 상수
//const float stiffness = 1048576.0;
//const float stiffness = 65536.0;
const float stiffness = 16384.0;
//const float stiffness = 8192.0;
//const float stiffness = 4096.0;
const float damping = 0.98;
//const float damping = 0.1;
const vec3 gravity = vec3(0.0, -9.8, 0.0);
const int WIDTH = 16;
const int HEIGHT = 16;
const int DEPTH = 16;
const int LOCAL_SIZE = 8;

float windStrength = 5.0; 
float frequency = 0.2; // 흔들리는 속도

void main() {
//    uint x = gl_GlobalInvocationID.x;
//    uint y = gl_GlobalInvocationID.y;
//    uint z = gl_GlobalInvocationID.z;
//
//    uint index = x + y * WIDTH + z * WIDTH * HEIGHT;
//
//    SphereNode current = nodesIn[index];
//    float invMass = (current.isFixed > 0.5) ? 0.0 : 1.0;
//
//    vec3 p = current.pos.xyz;
//    vec3 v = current.vel.xyz;
//    vec3 originPos = current.originPos.xyz;
//    vec3 prevPos = current.prevPos.xyz;
//    vec3 prevP = p;
//
//    vec3 wind = vec3(0.0, 0.0, sin(u_Time * frequency) * windStrength);
//    vec3 force = gravity + wind;
//
//    float sdt = dt / float(subStepCnt);
//    float alpha = 1.0 / stiffness;
//    float alpha_tilde = alpha / (sdt * sdt);
//
//    if (passType == 0) {
//        // --- STEP 0: 예측 위치 계산 (External Forces only) ---
//        constraints[index].lambda = 0.0;
//        if(index >= nodesIn.length()) return;
//
//        v *= pow(damping, 1.0 / float(subStepCnt));
//        vec3 externalAcc = force;
//
//        if(invMass > 0.0) {
//            p = p + v * sdt + externalAcc * sdt * sdt;
//        }
//        current.pos = vec4(p, 1.0);
//        nodesOut[index] = current;
//    } else if (passType == 1) {
//        // --- STEP 1: 제약 조건 해결 (Distance Constraints) ---
//    
//        if(invMass > 0.0) {
//            DistanceConstraint c = constraints[index];
//
//            float w1 = nodesIn[c.idx1].isFixed > 0.5 ? 0.0 : 1.0;
//            float w2 = nodesIn[c.idx2].isFixed > 0.5 ? 0.0 : 1.0;
//            float wSum = w1 + w2;
//
//            if (wSum <= 0.0) return;
//
//            vec3 pos1 = nodesIn[c.idx1].pos.xyz;
//            vec3 pos2 = nodesIn[c.idx2].pos.xyz;
//
//            vec3 diff = pos1 - pos2;
//            float dist = length(diff);
//            float C = dist - c.restLength;
//
//            float alpha_tilde = alpha / (sdt * sdt);
//            float dLambda = (-C - alpha_tilde * c.lambda) / (wSum + alpha_tilde);
//            c.lambda += dLambda;
//            constraints[index] = c;
//
//            vec3 grad = diff / max(dist, 0.0001);
//            vec3 dp1 = (w1 * dLambda) * grad;
//            vec3 dp2 = -(w2 * dLambda) * grad;
//            atomicAdd(nodesOut[c.idx1].pos.x, dp1.x);
//            atomicAdd(nodesOut[c.idx1].pos.y, dp1.y);
//            atomicAdd(nodesOut[c.idx1].pos.z, dp1.z);
//            atomicAdd(nodesOut[c.idx2].pos.x, dp2.x);
//            atomicAdd(nodesOut[c.idx2].pos.y, dp2.y);
//            atomicAdd(nodesOut[c.idx2].pos.z, dp2.z);
//        }
//    } else if (passType == 2) {
//        // --- STEP 2: 최종 위치 업데이트 ---
//        v = (p - prevPos) / sdt;
//        current.vel = vec4(v, 0.0);
//        current.prevPos = vec4(p, 1.0);
//        nodesOut[index] = current;
//    }
}